#!/bin/sh

# Copyright (C) 2011 Simon Josefsson

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test "x$2" = "xvn"; then
    VERSION=`$0 $1`
    MAJOR=`echo $VERSION | sed 's/^\([^.]*\)\..*/\1/g'`
    MINOR=`echo $VERSION | sed 's/^[^.]*\.\([^.]*\)\..*/\1/g'`
    PATCH=`echo $VERSION | sed 's/^[^.]*\.[^.]*\.\([^.]*\)\..*/\1/g'`
    printf "0x%02x%02x%02x00" $MAJOR $MINOR $PATCH
else
    `dirname $0`/git-version-gen $1 \
	's/[a-z-]*-\([0-9]*\)-\([0-9]*\)-\([0-9]*\)\(-\([0-9]*\)\)\?.*/v\1.\2.\3.\5/;s/\.$//'
fi
